[package]
edition = "2021"
rust-version = "1.60"

authors = ["Daniel Egger <daniel@eggers-club.de>"]
categories = [
    "embedded",
    "hardware-support",
    "no-std",
]
description = "Peripheral access API for STM32F4 series microcontrollers"
documentation = "https://docs.rs/stm32f4xx-hal"
keywords = [
    "arm",
    "cortex-m",
    "stm32f4xx",
    "hal",
]
license = "0BSD"
name = "stm32f4xx-hal"
readme = "README.md"
repository = "https://github.com/stm32-rs/stm32f4xx-hal"
version = "0.17.1"

[package.metadata.docs.rs]
features = ["stm32f429", "usb_fs", "can", "i2s", "fsmc_lcd", "rtic", "defmt"]
targets = ["thumbv7em-none-eabihf"]

[dependencies]
defmt = { version = "0.3.4", optional = true }
bxcan = { version = "0.7", optional = true }
cortex-m = { version = "0.7.7", features = ["critical-section-single-core"]}
cortex-m-rt = "0.7.3"
nb = "1.1"
rand_core = "0.6.4"
stm32f4 = "0.15.1"
synopsys-usb-otg = { version = "0.3.2", features = ["cortex-m"], optional = true }
sdio-host = { version = "0.6.0", optional = true }
embedded-dma = "0.2.0"
bare-metal = { version = "1" }
void = { default-features = false, version = "1.0.2" }
embedded-hal = { features = ["unproven"], version = "0.2.7" }
embedded-hal-nb = "1.0.0-alpha.3"
display-interface = { version = "0.4.1", optional = true }
fugit = "0.3.6"
fugit-timer = "0.1.3"
rtic-monotonic = { version = "1.0", optional = true }
systick-monotonic = { version = "1.0", optional = true }
bitflags = "2.2"
embedded-storage = "0.2"
arrayvec = "0.7.4"
[dependencies.time]
version = "0.3.14"
default-features = false

[dependencies.embedded-hal-one]
version = "=1.0.0-alpha.11"
package = "embedded-hal"

[dependencies.stm32_i2s_v12x]
version = "0.5.0"
optional = true

[dev-dependencies]
defmt = "0.3.4"
defmt-rtt = "0.4.0"
panic-probe = { version = "0.3.0", features = [ "print-defmt" ] }
panic-semihosting = "0.6.0"
cortex-m-semihosting = "0.5.0"
heapless = "0.7.16"
panic-halt = "0.2.0"
ssd1306 = "0.7.1"
embedded-graphics = "0.7.1"
usb-device = "0.2.9"
usbd-serial = "0.1.1"
micromath = "2"
cortex-m-rtic = { version = "1.1.4", features = ["test-critical-section"] }
dwt-systick-monotonic = "1.1"
st7789 = "0.7.0"
rtt-target = { version = "0.4.0" }
display-interface-spi = "0.4.1"
ist7920 = "0.1.1"
smart-leds = "0.3.0"
ws2812-spi = { version = "0.4.0", features = [] }
hd44780-driver = "0.4.0"
display-interface = "0.4"
ft6x06 = "0.1.2"
ushell = "0.3.5"

[dev-dependencies.time]
version = "0.3"
default-features = false
features = ["macros"]

[features]
device-selected = []
rt = [] # deprecated
# Note: stm32f4 has only one feature for some very similar device families,
# so it's intended for e.g. stm32f405/415 to both enable stm32f4/stm32f405.
stm32f401 = ["stm32f4/stm32f401", "device-selected", "gpio-f401",]
stm32f405 = ["stm32f4/stm32f405", "device-selected", "gpio-f417"]
stm32f407 = ["stm32f4/stm32f407", "device-selected", "gpio-f417"]
stm32f415 = ["stm32f4/stm32f405", "device-selected", "gpio-f417", "cryp"]
stm32f417 = ["stm32f4/stm32f407", "device-selected", "gpio-f417", "cryp"]
stm32f410 = ["stm32f4/stm32f410", "device-selected", "gpio-f410"]
stm32f411 = ["stm32f4/stm32f411", "device-selected", "gpio-f411"]
stm32f412 = ["stm32f4/stm32f412", "device-selected", "gpio-f412"]
stm32f413 = ["stm32f4/stm32f413", "device-selected", "gpio-f413"]
stm32f423 = ["stm32f4/stm32f413", "device-selected", "gpio-f413", "aes"]
stm32f427 = ["stm32f4/stm32f427", "device-selected", "gpio-f427", "fsmc"]
stm32f429 = ["stm32f4/stm32f429", "device-selected", "gpio-f427", "fmc"]
stm32f437 = ["stm32f4/stm32f427", "device-selected", "gpio-f427", "fsmc", "cryp"]
stm32f439 = ["stm32f4/stm32f429", "device-selected", "gpio-f427", "fmc", "cryp"]
stm32f446 = ["stm32f4/stm32f446", "device-selected", "gpio-f446"]
stm32f469 = ["stm32f4/stm32f469", "device-selected", "gpio-f469"]
stm32f479 = ["stm32f4/stm32f469", "device-selected", "gpio-f469", "cryp"]

gpio-f401 = [
    "gpiod", "gpioe",
    "i2c3",
    "otg-fs",
    "sdio",
    "spi3", "spi4",
    "tim1", "tim2", "tim3", "tim4", "tim5", "tim9", "tim10", "tim11",
]
gpio-f410 = [
    "dac",
    "fmpi2c1",
    "lptim1",
    "spi5",
    "tim1", "tim5", "tim6", "tim9", "tim11",
]
gpio-f411 = [
    "gpiod", "gpioe", # "gpioi",
    "i2c3",
    "otg-fs",
    "sdio",
    "tim1", "tim2", "tim3", "tim4", "tim5", "tim9", "tim10", "tim11",
    "spi3", "spi4", "spi5",
]
gpio-f412 = [
    "gpiod", "gpioe", "gpiof", "gpiog",
    "can1", "can2",
    "dfsdm1",
    "fmpi2c1",
    "fsmc",
    "i2c3",
    "quadspi",
    "otg-fs",
    "rng",
    "sdio",
    "spi3", "spi4", "spi5",
    "tim1", "tim2", "tim3", "tim4", "tim5", "tim6", "tim7", "tim8", "tim9", "tim10", "tim11", "tim12", "tim13", "tim14",
    "usart3",
]
gpio-f413 = [
    "gpiod", "gpioe", "gpiof", "gpiog",
    "can1", "can2", "can3",
    "dac",
    "dfsdm1",
    "dfsdm2",
    "fsmc",
    "fmpi2c1",
    "i2c3",
    "lptim1",
    "quadspi",
    "otg-fs",
    "rng",
    "sai1",
    "sdio",
    "spi3", "spi4", "spi5",
    "tim1", "tim2", "tim3", "tim4", "tim5", "tim6", "tim7", "tim8", "tim9", "tim10", "tim11", "tim12", "tim13", "tim14",
    "usart3", "uart4", "uart5", "uart7", "uart8", "uart9", "uart10",
]
gpio-f417 = [
    "gpiod", "gpioe", "gpiof", "gpiog", "gpioi",
    "adc2", "adc3",
    "can1", "can2",
    "dac",
    "dcmi",
    "eth",
    "fsmc",
    "i2c3",
    "otg-fs",
    "otg-hs",
    "rng",
    "sdio",
    "spi3",
    "tim1", "tim2", "tim3", "tim4", "tim5", "tim6", "tim7", "tim8", "tim9", "tim10", "tim11", "tim12", "tim13", "tim14",
    "usart3", "uart4", "uart5",
]
gpio-f427 = [
    "gpiod", "gpioe", "gpiof", "gpiog", "gpioi", "gpioj", "gpiok",
    "adc2", "adc3",
    "can1", "can2",
    "dac",
    "dcmi",
    "eth",
    "i2c3",
    "ltdc",
    "otg-fs",
    "otg-hs",
    "rng",
    "sai1",
    "sdio",
    "spi3", "spi4", "spi5", "spi6",
    "tim1", "tim2", "tim3", "tim4", "tim5", "tim6", "tim7", "tim8", "tim9", "tim10", "tim11", "tim12", "tim13", "tim14",
    "usart3", "uart4", "uart5", "uart7", "uart8",
]
gpio-f446 = [
    "gpiod", "gpioe", "gpiof", "gpiog",
    "adc2", "adc3",
    "can1", "can2",
    "dac",
    "dcmi",
    "fmpi2c1",
    "fmc",
    "i2c3",
    "quadspi",
    "otg-fs",
    "otg-hs",
    "sai1",
    "sai2",
    #"sdio",
    "spi3", "spi4",
    "spdifrx",
    "tim1", "tim2", "tim3", "tim4", "tim5", "tim6", "tim7", "tim8", "tim9", "tim10", "tim11", "tim12", "tim13", "tim14",
    "usart3", "uart4", "uart5",
]
gpio-f469 = [
    "gpiod", "gpioe", "gpiof", "gpiog", "gpioi", "gpioj", "gpiok",
    "adc2", "adc3",
    "can1", "can2",
    "dac",
    "dcmi",
    "dsihost",
    "eth",
    "fmc",
    "i2c3",
    "ltdc",
    "quadspi",
    "otg-fs",
    "otg-hs",
    "rng",
    "sai1",
    "sdio",
    "spi3", "spi4", "spi5", "spi6",
    "tim1", "tim2", "tim3", "tim4", "tim5", "tim6", "tim7", "tim8", "tim9", "tim10", "tim11", "tim12", "tim13", "tim14",
    "usart3", "uart4", "uart5", "uart7", "uart8",
]

usb_fs = ["synopsys-usb-otg", "synopsys-usb-otg/fs"]
usb_hs = ["synopsys-usb-otg", "synopsys-usb-otg/hs"]

can = ["bxcan"]

i2s = ["stm32_i2s_v12x"]

fsmc_lcd = ["display-interface"]

defmt = ["dep:defmt", "fugit/defmt", "nb/defmt-0-3"]
dfsdm = []
sai = []

adc2 = []
adc3 = []
aes = []
can1 = []
can2 = []
can3 = []
cryp = []
dac = []
dcmi = []
dfsdm1 = ["dfsdm"]
dfsdm2 = ["dfsdm"]
dsihost = []
eth = []
fmc = []
fsmc = []
fmpi2c1 = []
gpiod = []
gpioe = []
gpiof = []
gpiog = []
gpioi = []
gpioj = []
gpiok = []
i2c3 = []
lptim1 = []
ltdc = []
quadspi = []
otg-fs = []
otg-hs = []
rng = []
sai1 = ["sai"]
sai2 = ["sai"]
sdio = []
spi3 = []
spi4 = []
spi5 = []
spi6 = []
spdifrx = []
tim1 = []
tim2 = []
tim3 = []
tim4 = []
tim5 = []
tim6 = []
tim7 = []
tim8 = []
tim9 = []
tim10 = []
tim11 = []
tim12 = []
tim13 = []
tim14 = []
usart3 = []
uart4 = []
uart5 = []
uart7 = []
uart8 = []
uart9 = []
uart10 = []

rtic = ["rtic-monotonic", "systick-monotonic"]

[profile.dev]
debug = true
lto = true

[profile.release]
debug = true
lto = true
opt-level = "s"

# Keep examples sorted  


[[example]]
name = "display-touch"
required-features = ["fsmc_lcd", "stm32f413"] #or stm32f413


[[example]]
name = "f413disco-lcd-ferris"
required-features = ["gpiod", "gpioe", "gpiof", "gpiog", "fsmc", "fsmc_lcd"] # stm32f413

